---
language: node_js
node_js:
<<<<<<< HEAD
  - "4"
=======
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"
>>>>>>> 7c49161... message

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.yarn-cache

env:
<<<<<<< HEAD
  - EMBER_TRY_SCENARIO=1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=fastboot-addon-tests

matrix:
  fast_finish: true
=======
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
>>>>>>> 7c49161... message
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm install -g yarn
  - npm --version
<<<<<<< HEAD
  - yarn --version

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
=======

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
>>>>>>> 7c49161... message
